CREATE WAREHOUSE IF NOT EXISTS ANALYTICS_WH_DEV  WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60;
CREATE WAREHOUSE IF NOT EXISTS ANALYTICS_WH_TEST WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60;
CREATE WAREHOUSE IF NOT EXISTS ANALYTICS_WH_PROD WITH WAREHOUSE_SIZE = 'SMALL'  AUTO_SUSPEND = 120;

CREATE DATABASE IF NOT EXISTS ANALYTICS_DB_DEV;
CREATE DATABASE IF NOT EXISTS ANALYTICS_DB_TEST;
CREATE DATABASE IF NOT EXISTS ANALYTICS_DB_PROD;

CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH_DEV  TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH_TEST TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH_PROD TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE ANALYTICS_DB_DEV  TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE ANALYTICS_DB_TEST TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE ANALYTICS_DB_PROD TO ROLE TRANSFORMER;
GRANT CREATE SCHEMA ON DATABASE ANALYTICS_DB_DEV  TO ROLE TRANSFORMER;
GRANT CREATE SCHEMA ON DATABASE ANALYTICS_DB_TEST TO ROLE TRANSFORMER;
GRANT CREATE SCHEMA ON DATABASE ANALYTICS_DB_PROD TO ROLE TRANSFORMER;

CREATE ROLE IF NOT EXISTS ADF_LOADER;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH_DEV  TO ROLE ADF_LOADER;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH_TEST TO ROLE ADF_LOADER;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH_PROD TO ROLE ADF_LOADER;
GRANT USAGE ON DATABASE ANALYTICS_DB_DEV  TO ROLE ADF_LOADER;
GRANT USAGE ON DATABASE ANALYTICS_DB_TEST TO ROLE ADF_LOADER;
GRANT USAGE ON DATABASE ANALYTICS_DB_PROD TO ROLE ADF_LOADER;

GRANT ROLE TRANSFORMER TO USER SAMBU1998;
