CREATE SCHEMA IF NOT EXISTS RAW_SM;
CREATE SCHEMA IF NOT EXISTS STAGE_SM;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE_SM;
CREATE SCHEMA IF NOT EXISTS MARTS;

GRANT USAGE ON SCHEMA RAW_SM TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_SM TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_SM TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA STAGE_SM TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA INTERMEDIATE_SM TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA MARTS TO ROLE TRANSFORMER;

GRANT USAGE ON SCHEMA RAW_SM TO ROLE ADF_LOADER;
GRANT INSERT ON ALL TABLES IN SCHEMA RAW_SM TO ROLE ADF_LOADER;
GRANT INSERT ON FUTURE TABLES IN SCHEMA RAW_SM TO ROLE ADF_LOADER;
